{% set name = "polygonation" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polygonation-{{ version }}.tar.gz
  sha256: 70bc824d091a8eaa57a6c83b67b5bfeaf5ee65ff55f64b9d963c0b8b4516c896

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy
    - python >=3.7
    - scipy

test:
  imports:
    - polygonation
    - polygonation.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rwijtvliet/polygonation
  summary: Python package to tessellate a set of points in the plane with polygons.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rwijtvliet
